org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
kotlin.code.style=official
kotlin.mpp.stability.nowarn=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2
android.useAndroidX=true
android.targetSdk=35
android.compileSdk=35
android.minSdk=26
kotlin.version=1.9.22
agp.version=8.2.2
compose.version=1.5.12
