// DriverProfile feature types
// Generated by scaffold generator — follow the pattern, don't modify structure

export interface DriverProfileItem {
  uuid: string;
  // TODO: Add fields
}

export interface DriverProfileRequest {
  // TODO: Add request fields
}
