// CustomerSearch feature types
// Generated by scaffold generator — follow the pattern, don't modify structure

export interface CustomerSearchItem {
  uuid: string;
  // TODO: Add fields
}

export interface CustomerSearchRequest {
  // TODO: Add request fields
}
